stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/SeoulBikeData.csv
    outs:
    - data/raw/SeoulBikeData.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/SeoulBikeData.csv
    outs:
    - data/processed/train_SeoulBikeData.csv
    - data/processed/test_SeoulBikeData.csv


