base:
  project: seoulbike_project
  random_state: 42
  target_col: Rented Bike Count

data_source:
  s3_source: data_given/SeoulBikeData.csv

load_data:
  raw_dataset_csv: data/raw/SeoulBikeData.csv

split_data:
  train_path: data/processed/train_SeoulBikeData.csv
  test_path: data/processed/test_SeoulBikeData.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models

# reports:
#   params: report/params.json
#   scores: report/scores.json

# webapp_model_dir: prediction_service/model/model.joblib